name: CI

on:
  workflow_call:
  pull_request:
  schedule:
    # NOTE: We run this weekly at 1 am UTC on every Saturday
    - cron:  '0 1 * * 6'

jobs:
  # This is based on this workflow, with an additional test env setup method
  # StackStorm-Exchange/ci/.github/workflows/pack-build_and_test.yaml@master

  build_and_test:
    runs-on: ubuntu-latest
    name: 'Build and Test / Python ${{ matrix.python-version-short }}'
    strategy:
      matrix:
        include:
          - python-version-short: 3.6
            python-version: 3.6.13
    steps:
      - name: Checkout Pack Repo and CI Repos
        uses: StackStorm-Exchange/ci/.github/actions/checkout@master

      - name: Install APT Dependencies
        uses: StackStorm-Exchange/ci/.github/actions/apt-dependencies@master
        with:
          cache-version: v0

      - name: Install Python Dependencies
        uses: StackStorm-Exchange/ci/.github/actions/py-dependencies@master
        with:
          cache-version: v0
          python-version: ${{ matrix.python-version }}

      - name: Install consul, vault, python hvac
        shell: bash
        run: |
          tests/setup_testing_env.sh

      - name: Update virtualenv activate script
        # This works around an infinite recursion error with newer requests+ssl+eventlet.
        # eventlet monkey_patch as early as possible (has to be in activate as nosetests gets reinstalled during test phase)
        # See: https://github.com/StackStorm-Exchange/stackstorm-vault/pull/23
        run: |
          echo "grep -q monkey_patch ${VIRTUALENV_DIR}/bin/nosetests || sed -i -e '/^import re$/i from st2common.util.monkey_patch import monkey_patch\nmonkey_patch()\n' ${VIRTUALENV_DIR}/bin/nosetests" >> ${VIRTUALENV_DIR}/bin/activate
          echo "grep -q pyopenssl\\.inject ${VIRTUALENV_DIR}/bin/nosetests || sed -i -e '/^import re$/i from urllib3.contrib import pyopenssl\npyopenssl.inject_into_urllib3()\n' ${VIRTUALENV_DIR}/bin/nosetests" >> ${VIRTUALENV_DIR}/bin/activate

      - name: Run pack tests
        uses: StackStorm-Exchange/ci/.github/actions/test@master
        with:
          enable-common-libs: false

    services:
      mongo:
        image: mongo:3.4
        ports:
          - 27017:27017
      rabbitmq:
        image: rabbitmq:3
        ports:
          - 5672:5672
      #redis:
      #  image: redis
      #  ports:
      #    - 6379:6379
